### ISSUE TITLE
pywin32==305.1

### ISSUE THREAD

**Issue by Wangjinhong1998** [Xiaohao-Xu/Customizable-VLM#2]
Hello, congratulations on achieving such forward-looking progress in your work. I have a question: Isn't the package pywin32==305.1 used under the Windows system? Are you running the program locally, rather than on a server?

**Comment by Xiaohao-Xu** [comment]
Hi Jinhong,Thank you for your interest!Yeah. We have used the Windows OS to run the experiments.The experiments are easy (time-efficient and hardware-friendly) to run. Thus，we just run them locally. Feel free to try it on other OS (maybe with minor modifications)!Sent from my iPhoneOn May 13, 2024, at 10:33 PM, Wangjinhong1998 ***@***.***> wrote:﻿
Hello, congratulations on achieving such forward-looking progress in your work. I have a question: Isn't the package pywin32==305.1 used under the Windows system? Are you running the program locally, rather than on a server?

**Comment by Wangjinhong1998** [comment]
> Hi Jinhong,Thank you for your interest!Yeah. We have used the Windows OS to run the experiments.The experiments are easy (time-efficient and hardware-friendly) to run. Thus，we just run them locally. Feel free to try it on other OS (maybe with minor modifications)!Sent from my iPhoneOn May 13, 2024, at 10:33 PM, Wangjinhong1998 ***@***.***> wrote:﻿ Hello, congratulations on achieving such forward-looking progress in your work. I have a question: Isn't the package pywin32==305.1 used under the Windows system? Are you running the program locally, rather than on a server? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thank you for your help and congratulations again on your achievement. I have another question to ask: due to my insufficient API quota, I may not be able to run the results of your code. May I know if Table 1 in the paper, which shows the performance results of the entire dataset, was directly obtained from the code you have made public? I haven’t tried using large models to process the entire dataset before, so I am quite surprised and impressed by your work

**Comment by Xiaohao-Xu** [comment]
Yep, the code is used to reproduce the result in Table 1. If you do not have sufficient commercial API quota (e.g., from OpenAI), my suggestion is to use free API (e.g., the API of Gemini from Google) or use other open-sourced VLM/LLM for further exploration. : )
